package com.voicereminder.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Environment
import android.util.Log
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfGenerator {
    private const val TAG = "PdfGenerator"

    // A4 dimensions at 72 DPI
    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 48
    private const val CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2)

    /**
     * Generates a multi-page, formatted PDF from document title and Markdown content.
     */
    fun generateDocumentPdf(context: Context, title: String, content: String): File? {
        val pdfDoc = PdfDocument()

        try {
            val titlePaint = Paint().apply {
                color = Color.rgb(30, 27, 75) // Deep Indigo #1E1B4B
                textSize = 22f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val subtitlePaint = Paint().apply {
                color = Color.rgb(107, 114, 128) // Gray 500
                textSize = 10f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
                isAntiAlias = true
            }

            val headerPaint = Paint().apply {
                color = Color.rgb(79, 70, 229) // Indigo 600
                textSize = 14f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val bodyPaint = Paint().apply {
                color = Color.rgb(31, 41, 55) // Gray 800
                textSize = 11f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                isAntiAlias = true
            }

            val bulletPaint = Paint().apply {
                color = Color.rgb(16, 185, 129) // Emerald 500
                textSize = 11f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val linePaint = Paint().apply {
                color = Color.rgb(229, 231, 235) // Gray 200
                strokeWidth = 1.5f
                isAntiAlias = true
            }

            var pageNumber = 1
            var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            var page = pdfDoc.startPage(pageInfo)
            var canvas = page.canvas

            var y = MARGIN.toFloat() + 20f

            // 1. Draw Title & Meta Header
            val cleanTitle = title.replace(Regex("^#+\\s*"), "").trim()
            canvas.drawText(cleanTitle, MARGIN.toFloat(), y, titlePaint)
            y += 24f

            val dateStr = SimpleDateFormat("MMMM dd, yyyy · hh:mm a", Locale.getDefault()).format(Date())
            canvas.drawText("Generated by VoiceReminder AI Assistant · $dateStr", MARGIN.toFloat(), y, subtitlePaint)
            y += 16f

            canvas.drawLine(MARGIN.toFloat(), y, (PAGE_WIDTH - MARGIN).toFloat(), y, linePaint)
            y += 24f

            // 2. Parse Lines and format
            val lines = content.lines()
            for (rawLine in lines) {
                val line = rawLine.trim()

                // Check for new page
                if (y > PAGE_HEIGHT - MARGIN - 30f) {
                    pdfDoc.finishPage(page)
                    pageNumber++
                    pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
                    page = pdfDoc.startPage(pageInfo)
                    canvas = page.canvas
                    y = MARGIN.toFloat() + 20f
                }

                when {
                    line.isBlank() -> {
                        y += 8f
                    }
                    line.startsWith("# ") -> {
                        // Skip if same as title
                        if (!line.contains(cleanTitle, ignoreCase = true)) {
                            y += 12f
                            canvas.drawText(line.removePrefix("#").trim(), MARGIN.toFloat(), y, titlePaint)
                            y += 18f
                        }
                    }
                    line.startsWith("## ") || line.startsWith("### ") -> {
                        y += 12f
                        val sectionText = line.replace(Regex("^#+\\s*"), "").trim()
                        canvas.drawText(sectionText, MARGIN.toFloat(), y, headerPaint)
                        y += 18f
                    }
                    line.startsWith("- ") || line.startsWith("* ") -> {
                        val bulletContent = line.substring(2).trim()
                        canvas.drawText("•", MARGIN.toFloat(), y, bulletPaint)
                        y = drawWrappedText(canvas, bulletContent, MARGIN.toFloat() + 14f, y, CONTENT_WIDTH - 14f, bodyPaint)
                        y += 4f
                    }
                    else -> {
                        y = drawWrappedText(canvas, line, MARGIN.toFloat(), y, CONTENT_WIDTH.toFloat(), bodyPaint)
                        y += 4f
                    }
                }
            }

            pdfDoc.finishPage(page)

            // Save to file
            val safeName = cleanTitle.replace(Regex("[^a-zA-Z0-9_-]"), "_").take(40)
            val dir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS) ?: context.filesDir
            if (!dir.exists()) dir.mkdirs()
            val outputFile = File(dir, "${safeName}.pdf")

            FileOutputStream(outputFile).use { out ->
                pdfDoc.writeTo(out)
            }
            Log.i(TAG, "PDF generated successfully at: ${outputFile.absolutePath}")
            return outputFile

        } catch (e: Exception) {
            Log.e(TAG, "Error generating PDF: ${e.message}", e)
            return null
        } finally {
            pdfDoc.close()
        }
    }

    /**
     * Draw text wrapped to fit maxWidth, returns the next available Y coordinate.
     */
    private fun drawWrappedText(canvas: Canvas, text: String, x: Float, startY: Float, maxWidth: Float, paint: Paint): Float {
        var currentY = startY
        val words = text.split(" ")
        var currentLine = ""

        for (word in words) {
            val testLine = if (currentLine.isEmpty()) word else "$currentLine $word"
            val width = paint.measureText(testLine)

            if (width > maxWidth && currentLine.isNotEmpty()) {
                canvas.drawText(currentLine, x, currentY, paint)
                currentY += 15f
                currentLine = word
            } else {
                currentLine = testLine
            }
        }

        if (currentLine.isNotEmpty()) {
            canvas.drawText(currentLine, x, currentY, paint)
            currentY += 15f
        }

        return currentY
    }

    /**
     * Opens the generated PDF in an external viewer (Google Drive / Adobe Reader / system viewer).
     */
    fun openPdf(context: Context, file: File): Boolean {
        return try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
            val intent = Intent(Intent.ACTION_VIEW).apply {
                setDataAndType(uri, "application/pdf")
                flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_GRANT_READ_URI_PERMISSION
            }
            context.startActivity(intent)
            true
        } catch (e: Exception) {
            Log.e(TAG, "Could not open PDF viewer: ${e.message}", e)
            false
        }
    }

    /**
     * Shares the generated PDF via WhatsApp, Email, Drive, etc.
     */
    fun sharePdf(context: Context, file: File): Boolean {
        return try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_GRANT_READ_URI_PERMISSION
            }
            val chooser = Intent.createChooser(intent, "Share Document PDF").apply {
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
            context.startActivity(chooser)
            true
        } catch (e: Exception) {
            Log.e(TAG, "Could not share PDF: ${e.message}", e)
            false
        }
    }
}
